name: plan_my_escape
description: Projet de développement mobile pour le cour d'archi log
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2     # Icons
  calendar_view: ^1.0.4       # Calendrier
  shared_preferences: ^2.0.8  # Sauvegarder les données
  intl: ^0.17.0               # Gérer les dates
  path_provider: ^2.0.5       # Gérer les fichiers
  share: ^2.0.4               # Partager les données
  # google_maps_flutter: ^2.0.9 # Plan B mais ça demande une clé API
  # flutter_map: ^6.0.1 # Maps
  geolocator: ^10.0.0         # Gérer la localisation
  url_launcher: ^6.0.12       # Ouvrir des liens


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

